# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(369, 126)
        Form.setMinimumSize(QtCore.QSize(369, 126))
        Form.setMaximumSize(QtCore.QSize(369, 126))
        Form.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(240, 240, 240);")
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setContentsMargins(6, 0, 6, 0)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(0, 36))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 18pt \"微软雅黑\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(100, 36))
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt \"微软雅黑\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.hour = QtWidgets.QLineEdit(Form)
        self.hour.setMinimumSize(QtCore.QSize(0, 36))
        self.hour.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt \"微软雅黑\";")
        self.hour.setAlignment(QtCore.Qt.AlignCenter)
        self.hour.setObjectName("hour")
        self.horizontalLayout.addWidget(self.hour)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setMinimumSize(QtCore.QSize(0, 36))
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 20pt \"微软雅黑\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.minutes = QtWidgets.QLineEdit(Form)
        self.minutes.setMinimumSize(QtCore.QSize(0, 36))
        self.minutes.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt \"微软雅黑\";")
        self.minutes.setAlignment(QtCore.Qt.AlignCenter)
        self.minutes.setObjectName("minutes")
        self.horizontalLayout.addWidget(self.minutes)
        self.ok = QtWidgets.QPushButton(Form)
        self.ok.setMinimumSize(QtCore.QSize(100, 36))
        self.ok.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ok.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"微软雅黑\";\n"
"color: rgb(85, 85, 255);")
        self.ok.setObjectName("ok")
        self.horizontalLayout.addWidget(self.ok)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setMinimumSize(QtCore.QSize(100, 36))
        self.label_4.setMaximumSize(QtCore.QSize(100, 36))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt \"微软雅黑\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.countdown = QtWidgets.QLabel(Form)
        self.countdown.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);\n"
"font: 16pt \"微软雅黑\";")
        self.countdown.setAlignment(QtCore.Qt.AlignCenter)
        self.countdown.setObjectName("countdown")
        self.horizontalLayout_2.addWidget(self.countdown)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "24小时制"))
        self.label_2.setText(_translate("Form", "时间"))
        self.hour.setText(_translate("Form", "09"))
        self.label_5.setText(_translate("Form", ":"))
        self.minutes.setText(_translate("Form", "00"))
        self.ok.setText(_translate("Form", "确定"))
        self.label_4.setText(_translate("Form", "倒计时"))
        self.countdown.setText(_translate("Form", "00:00:00"))
