# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1439, 720)
        Form.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);\n"
"font: 16pt \"微软雅黑\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(0, 40))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"微软雅黑\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.input_string = QtWidgets.QTextEdit(Form)
        self.input_string.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"微软雅黑\";")
        self.input_string.setObjectName("input_string")
        self.verticalLayout_2.addWidget(self.input_string)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setMinimumSize(QtCore.QSize(80, 40))
        self.label_7.setMaximumSize(QtCore.QSize(80, 40))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"微软雅黑\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.old_translate_path = QtWidgets.QLabel(Form)
        self.old_translate_path.setMinimumSize(QtCore.QSize(0, 40))
        self.old_translate_path.setMaximumSize(QtCore.QSize(16777215, 40))
        self.old_translate_path.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"微软雅黑\";\n"
"color: rgb(85, 85, 255);")
        self.old_translate_path.setText("")
        self.old_translate_path.setAlignment(QtCore.Qt.AlignCenter)
        self.old_translate_path.setObjectName("old_translate_path")
        self.horizontalLayout_3.addWidget(self.old_translate_path)
        self.copy_translate_path = QtWidgets.QPushButton(Form)
        self.copy_translate_path.setMaximumSize(QtCore.QSize(75, 30))
        self.copy_translate_path.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"font: 12pt \"微软雅黑\";\n"
"color: rgb(255, 255, 255);")
        self.copy_translate_path.setObjectName("copy_translate_path")
        self.horizontalLayout_3.addWidget(self.copy_translate_path)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.input_translate_path = QtWidgets.QTextEdit(Form)
        self.input_translate_path.setMinimumSize(QtCore.QSize(0, 60))
        self.input_translate_path.setMaximumSize(QtCore.QSize(16777215, 60))
        self.input_translate_path.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);\n"
"font: 16pt \"微软雅黑\";")
        self.input_translate_path.setObjectName("input_translate_path")
        self.verticalLayout_2.addWidget(self.input_translate_path)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setMinimumSize(QtCore.QSize(80, 40))
        self.label_6.setMaximumSize(QtCore.QSize(80, 40))
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"微软雅黑\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.old_project_path = QtWidgets.QLabel(Form)
        self.old_project_path.setMinimumSize(QtCore.QSize(440, 40))
        self.old_project_path.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"微软雅黑\";\n"
"color: rgb(85, 85, 255);")
        self.old_project_path.setText("")
        self.old_project_path.setAlignment(QtCore.Qt.AlignCenter)
        self.old_project_path.setObjectName("old_project_path")
        self.horizontalLayout_5.addWidget(self.old_project_path)
        self.copy_project_path = QtWidgets.QPushButton(Form)
        self.copy_project_path.setMaximumSize(QtCore.QSize(75, 30))
        self.copy_project_path.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"font: 12pt \"微软雅黑\";\n"
"color: rgb(255, 255, 255);")
        self.copy_project_path.setObjectName("copy_project_path")
        self.horizontalLayout_5.addWidget(self.copy_project_path)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.input_project_path = QtWidgets.QTextEdit(Form)
        self.input_project_path.setMinimumSize(QtCore.QSize(0, 60))
        self.input_project_path.setMaximumSize(QtCore.QSize(16777215, 60))
        self.input_project_path.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);\n"
"font: 16pt \"微软雅黑\";")
        self.input_project_path.setObjectName("input_project_path")
        self.verticalLayout_2.addWidget(self.input_project_path)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.check_copy_string = QtWidgets.QPushButton(Form)
        self.check_copy_string.setMinimumSize(QtCore.QSize(100, 40))
        self.check_copy_string.setMaximumSize(QtCore.QSize(100, 40))
        self.check_copy_string.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"font: 12pt \"微软雅黑\";\n"
"color: rgb(255, 255, 255);")
        self.check_copy_string.setObjectName("check_copy_string")
        self.horizontalLayout_6.addWidget(self.check_copy_string)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6.addWidget(self.frame)
        self.copy_string = QtWidgets.QPushButton(Form)
        self.copy_string.setMinimumSize(QtCore.QSize(100, 40))
        self.copy_string.setMaximumSize(QtCore.QSize(100, 40))
        self.copy_string.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"font: 12pt \"微软雅黑\";\n"
"color: rgb(255, 255, 255);")
        self.copy_string.setObjectName("copy_string")
        self.horizontalLayout_6.addWidget(self.copy_string)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6.addWidget(self.frame_2)
        self.delete_string = QtWidgets.QPushButton(Form)
        self.delete_string.setMinimumSize(QtCore.QSize(100, 40))
        self.delete_string.setMaximumSize(QtCore.QSize(100, 40))
        self.delete_string.setStyleSheet("background-color: rgb(255, 85, 127);\n"
"font: 12pt \"微软雅黑\";\n"
"color: rgb(255, 255, 255);")
        self.delete_string.setObjectName("delete_string")
        self.horizontalLayout_6.addWidget(self.delete_string)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6.addWidget(self.frame_3)
        self.open_copy_logo = QtWidgets.QPushButton(Form)
        self.open_copy_logo.setMinimumSize(QtCore.QSize(100, 40))
        self.open_copy_logo.setMaximumSize(QtCore.QSize(100, 40))
        self.open_copy_logo.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"font: 12pt \"微软雅黑\";\n"
"color: rgb(255, 255, 255);")
        self.open_copy_logo.setObjectName("open_copy_logo")
        self.horizontalLayout_6.addWidget(self.open_copy_logo)
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.open_delete_log = QtWidgets.QPushButton(Form)
        self.open_delete_log.setMinimumSize(QtCore.QSize(100, 40))
        self.open_delete_log.setMaximumSize(QtCore.QSize(100, 40))
        self.open_delete_log.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"font: 12pt \"微软雅黑\";\n"
"color: rgb(255, 255, 255);")
        self.open_delete_log.setObjectName("open_delete_log")
        self.horizontalLayout_6.addWidget(self.open_delete_log)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setMinimumSize(QtCore.QSize(0, 40))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);\n"
"font: 16pt \"微软雅黑\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.translate_statistics_find_string = QtWidgets.QLineEdit(Form)
        self.translate_statistics_find_string.setMinimumSize(QtCore.QSize(0, 40))
        self.translate_statistics_find_string.setMaximumSize(QtCore.QSize(16777215, 40))
        self.translate_statistics_find_string.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"微软雅黑\";\n"
"color: rgb(85, 85, 255);")
        self.translate_statistics_find_string.setObjectName("translate_statistics_find_string")
        self.horizontalLayout_4.addWidget(self.translate_statistics_find_string)
        self.translate_statistics_click_find = QtWidgets.QPushButton(Form)
        self.translate_statistics_click_find.setMinimumSize(QtCore.QSize(80, 40))
        self.translate_statistics_click_find.setMaximumSize(QtCore.QSize(80, 40))
        self.translate_statistics_click_find.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"微软雅黑\";")
        self.translate_statistics_click_find.setObjectName("translate_statistics_click_find")
        self.horizontalLayout_4.addWidget(self.translate_statistics_click_find)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.translate_statistics_list = QtWidgets.QTableWidget(Form)
        self.translate_statistics_list.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.translate_statistics_list.setObjectName("translate_statistics_list")
        self.translate_statistics_list.setColumnCount(0)
        self.translate_statistics_list.setRowCount(0)
        self.verticalLayout_3.addWidget(self.translate_statistics_list)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.refersh_translate_statistics = QtWidgets.QPushButton(Form)
        self.refersh_translate_statistics.setMinimumSize(QtCore.QSize(100, 40))
        self.refersh_translate_statistics.setMaximumSize(QtCore.QSize(100, 40))
        self.refersh_translate_statistics.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"font: 12pt \"微软雅黑\";\n"
"color: rgb(255, 255, 255);")
        self.refersh_translate_statistics.setObjectName("refersh_translate_statistics")
        self.horizontalLayout_2.addWidget(self.refersh_translate_statistics)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "拷贝区域"))
        self.label_2.setText(_translate("Form", "需要拷贝的字符，格式如下：<string name=\"i_joy_soft\">IJoySoft</string>"))
        self.label_7.setText(_translate("Form", "翻译路径:"))
        self.copy_translate_path.setText(_translate("Form", "使用"))
        self.label_6.setText(_translate("Form", "项目路径:"))
        self.copy_project_path.setText(_translate("Form", "使用"))
        self.check_copy_string.setText(_translate("Form", "查重拷贝"))
        self.copy_string.setText(_translate("Form", "拷贝"))
        self.delete_string.setText(_translate("Form", "删除"))
        self.open_copy_logo.setText(_translate("Form", "Log-拷贝"))
        self.open_delete_log.setText(_translate("Form", "Log-删除"))
        self.label_4.setText(_translate("Form", "翻译统计区域"))
        self.translate_statistics_click_find.setText(_translate("Form", "查找"))
        self.refersh_translate_statistics.setText(_translate("Form", "刷新"))
