# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1035, 500)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setMinimumSize(QtCore.QSize(180, 40))
        self.label_4.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"微软雅黑\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.input_001 = QtWidgets.QTextEdit(Form)
        self.input_001.setMinimumSize(QtCore.QSize(0, 40))
        self.input_001.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);\n"
"font: 12pt \"微软雅黑\";")
        self.input_001.setObjectName("input_001")
        self.horizontalLayout_2.addWidget(self.input_001)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setMinimumSize(QtCore.QSize(180, 40))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"微软雅黑\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.input_002 = QtWidgets.QTextEdit(Form)
        self.input_002.setMinimumSize(QtCore.QSize(0, 40))
        self.input_002.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);\n"
"font: 12pt \"微软雅黑\";")
        self.input_002.setObjectName("input_002")
        self.horizontalLayout_6.addWidget(self.input_002)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(180, 40))
        self.label.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"微软雅黑\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.input_003 = QtWidgets.QTextEdit(Form)
        self.input_003.setMinimumSize(QtCore.QSize(0, 40))
        self.input_003.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);\n"
"font: 12pt \"微软雅黑\";")
        self.input_003.setObjectName("input_003")
        self.horizontalLayout.addWidget(self.input_003)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(180, 40))
        self.label_2.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"微软雅黑\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.input_004 = QtWidgets.QTextEdit(Form)
        self.input_004.setMinimumSize(QtCore.QSize(0, 40))
        self.input_004.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);\n"
"font: 12pt \"微软雅黑\";")
        self.input_004.setObjectName("input_004")
        self.horizontalLayout_5.addWidget(self.input_004)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(180, 40))
        self.label_3.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"微软雅黑\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.input_005 = QtWidgets.QTextEdit(Form)
        self.input_005.setMinimumSize(QtCore.QSize(0, 40))
        self.input_005.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);\n"
"font: 12pt \"微软雅黑\";")
        self.input_005.setObjectName("input_005")
        self.horizontalLayout_3.addWidget(self.input_005)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setMinimumSize(QtCore.QSize(120, 50))
        self.frame_2.setMaximumSize(QtCore.QSize(120, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.remove_suffix = QtWidgets.QPushButton(self.frame_2)
        self.remove_suffix.setGeometry(QtCore.QRect(0, 10, 120, 40))
        self.remove_suffix.setMinimumSize(QtCore.QSize(120, 40))
        self.remove_suffix.setMaximumSize(QtCore.QSize(120, 40))
        self.remove_suffix.setStyleSheet("background-color: rgb(255, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"微软雅黑\";")
        self.remove_suffix.setObjectName("remove_suffix")
        self.horizontalLayout_4.addWidget(self.frame_2)
        self.frame_6 = QtWidgets.QFrame(Form)
        self.frame_6.setMinimumSize(QtCore.QSize(120, 50))
        self.frame_6.setMaximumSize(QtCore.QSize(120, 50))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.modify_suffix = QtWidgets.QPushButton(self.frame_6)
        self.modify_suffix.setGeometry(QtCore.QRect(0, 10, 120, 40))
        self.modify_suffix.setMinimumSize(QtCore.QSize(120, 40))
        self.modify_suffix.setMaximumSize(QtCore.QSize(120, 40))
        self.modify_suffix.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"微软雅黑\";")
        self.modify_suffix.setObjectName("modify_suffix")
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(Form)
        self.frame_8.setMinimumSize(QtCore.QSize(120, 50))
        self.frame_8.setMaximumSize(QtCore.QSize(120, 50))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.bandizip = QtWidgets.QPushButton(self.frame_8)
        self.bandizip.setGeometry(QtCore.QRect(0, 10, 120, 40))
        self.bandizip.setMinimumSize(QtCore.QSize(120, 40))
        self.bandizip.setMaximumSize(QtCore.QSize(120, 40))
        self.bandizip.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"微软雅黑\";")
        self.bandizip.setObjectName("bandizip")
        self.horizontalLayout_4.addWidget(self.frame_8)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(120, 50))
        self.frame.setMaximumSize(QtCore.QSize(120, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.delete_frame = QtWidgets.QPushButton(self.frame)
        self.delete_frame.setEnabled(True)
        self.delete_frame.setGeometry(QtCore.QRect(0, 10, 120, 40))
        self.delete_frame.setMinimumSize(QtCore.QSize(120, 40))
        self.delete_frame.setMaximumSize(QtCore.QSize(120, 40))
        self.delete_frame.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"微软雅黑\";")
        self.delete_frame.setObjectName("delete_frame")
        self.horizontalLayout_4.addWidget(self.frame)
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setMinimumSize(QtCore.QSize(120, 50))
        self.frame_4.setMaximumSize(QtCore.QSize(120, 50))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.log_remove_suffix = QtWidgets.QPushButton(self.frame_4)
        self.log_remove_suffix.setGeometry(QtCore.QRect(0, 10, 120, 40))
        self.log_remove_suffix.setMinimumSize(QtCore.QSize(120, 40))
        self.log_remove_suffix.setMaximumSize(QtCore.QSize(120, 40))
        self.log_remove_suffix.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"微软雅黑\";")
        self.log_remove_suffix.setObjectName("log_remove_suffix")
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.frame_10 = QtWidgets.QFrame(Form)
        self.frame_10.setMinimumSize(QtCore.QSize(120, 50))
        self.frame_10.setMaximumSize(QtCore.QSize(120, 50))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.log_modify_suffix = QtWidgets.QPushButton(self.frame_10)
        self.log_modify_suffix.setGeometry(QtCore.QRect(0, 10, 120, 40))
        self.log_modify_suffix.setMinimumSize(QtCore.QSize(120, 40))
        self.log_modify_suffix.setMaximumSize(QtCore.QSize(120, 40))
        self.log_modify_suffix.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"微软雅黑\";")
        self.log_modify_suffix.setObjectName("log_modify_suffix")
        self.horizontalLayout_4.addWidget(self.frame_10)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setMinimumSize(QtCore.QSize(120, 50))
        self.frame_3.setMaximumSize(QtCore.QSize(120, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.log_bandizip = QtWidgets.QPushButton(self.frame_3)
        self.log_bandizip.setGeometry(QtCore.QRect(0, 10, 120, 40))
        self.log_bandizip.setMinimumSize(QtCore.QSize(120, 40))
        self.log_bandizip.setMaximumSize(QtCore.QSize(120, 40))
        self.log_bandizip.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"微软雅黑\";")
        self.log_bandizip.setObjectName("log_bandizip")
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "旧文件名(包含的字符)"))
        self.label_5.setText(_translate("Form", "新文件名"))
        self.label.setText(_translate("Form", "旧后缀"))
        self.label_2.setText(_translate("Form", "新后缀"))
        self.label_3.setText(_translate("Form", "工作路径"))
        self.remove_suffix.setText(_translate("Form", "一键去后缀"))
        self.modify_suffix.setText(_translate("Form", "修改后缀"))
        self.bandizip.setText(_translate("Form", "压缩"))
        self.delete_frame.setText(_translate("Form", "删除Frame"))
        self.log_remove_suffix.setText(_translate("Form", "Log-一键"))
        self.log_modify_suffix.setText(_translate("Form", "Log-修改"))
        self.log_bandizip.setText(_translate("Form", "Log-压缩"))
