import hashlib
import os
import shutil
import subprocess
import sys

from version import APP_EXE_NAME, APP_VERSION, CACHE_DIR_NAME, RELEASE_EXE_NAME


def _pyinstaller_base(script_dir):
    image_dir = os.path.join(script_dir, 'image')
    return [
        sys.executable, '-m', 'PyInstaller',
        '--clean', '--noupx', '-w',
        '--paths', os.path.join(script_dir, '..'),
        '-i', os.path.join(image_dir, 'fast.ico'),
        '--add-data', f'{image_dir}{os.pathsep}image',
        '--hidden-import', 'magic',
        '--hidden-import', 'filetype',
        '--hidden-import', 'modify_suffix.file_type',
        '--hidden-import', 'modify_suffix.result_dialog',
        '--hidden-import', 'pylnk3',
        '--exclude-module', 'tkinter',
        '--exclude-module', 'matplotlib',
        '--exclude-module', 'numpy',
        '--exclude-module', 'scipy',
        '--exclude-module', 'pandas',
    ]


def _build_app_onedir(script_dir):
    dist_dir = os.path.join(script_dir, 'dist')
    app_dir = os.path.join(dist_dir, APP_EXE_NAME)
    if os.path.isdir(app_dir):
        shutil.rmtree(app_dir)

    cmd = _pyinstaller_base(script_dir) + [
        '-D', '-n', APP_EXE_NAME,
        os.path.join(script_dir, 'run.py'),
    ]
    subprocess.check_call(cmd, cwd=script_dir)
    return app_dir


def _write_bundle_meta(script_dir, bundle_zip):
    digest = hashlib.sha256()
    with open(bundle_zip, 'rb') as file:
        for chunk in iter(lambda: file.read(1024 * 1024), b''):
            digest.update(chunk)

    meta_path = os.path.join(script_dir, 'bundle_meta.py')
    with open(meta_path, 'w', encoding='utf-8', newline='\n') as file:
        file.write(
            '# Auto-generated by release.py. Do not edit.\n'
            f'APP_VERSION = {APP_VERSION!r}\n'
            f'BUNDLE_SHA256 = {digest.hexdigest()!r}\n'
            f'APP_EXE_NAME = {APP_EXE_NAME!r}\n'
            f'CACHE_DIR_NAME = {CACHE_DIR_NAME!r}\n'
        )
    return meta_path


def _create_bundle_zip(script_dir, app_dir):
    build_dir = os.path.join(script_dir, 'build')
    os.makedirs(build_dir, exist_ok=True)
    bundle_base = os.path.join(build_dir, 'bundle')
    bundle_zip = f'{bundle_base}.zip'
    if os.path.exists(bundle_zip):
        os.remove(bundle_zip)

    shutil.make_archive(bundle_base, 'zip', app_dir)
    return bundle_zip


def _build_launcher_onefile(script_dir, bundle_zip):
    image_dir = os.path.join(script_dir, 'image')
    launcher_script = os.path.join(script_dir, 'launcher.py')
    cmd = [
        sys.executable, '-m', 'PyInstaller',
        '-F', '--clean', '--noupx', '-w',
        '--paths', os.path.join(script_dir, '..'),
        '--paths', script_dir,
        '-n', RELEASE_EXE_NAME,
        '-i', os.path.join(image_dir, 'fast.ico'),
        '--add-data', f'{bundle_zip}{os.pathsep}.',
        '--hidden-import', 'bundle_meta',
        launcher_script,
    ]
    subprocess.check_call(cmd, cwd=script_dir)


if __name__ == '__main__':
    script_dir = os.path.dirname(os.path.abspath(__file__))
    app_dir = _build_app_onedir(script_dir)
    bundle_zip = _create_bundle_zip(script_dir, app_dir)
    _write_bundle_meta(script_dir, bundle_zip)
    _build_launcher_onefile(script_dir, bundle_zip)
    shutil.rmtree(app_dir, ignore_errors=True)
    print(f'打包完成: dist/{RELEASE_EXE_NAME}.exe')
    print(f'版本 {APP_VERSION}；分发单个 exe 即可')
    print('版本变化后将自动更新本地缓存并清理旧版本')
